### ISSUE TITLE
Erpnext Issue inserting a new Item

### ISSUE THREAD

**Issue by codrotech** [Myddleware/myddleware#130]
It seems like is looking for the Tab Item Attribute   "Size, Color... "  but an item can be created with not Item Attributes.

Thanks

See error below.

Traceback (most recent call last): File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application response = frappe.api.handle() File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 119, in handle "data": frappe.get_doc(data).insert().as_dict() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 221, in insert self.run_before_save_methods() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 862, in run_before_save_methods self.run_method("validate") File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 758, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1027, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1010, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 752, in <lambda> fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/item/item.py", line 95, in validate self.validate_attributes() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/item/item.py", line 669, in validate_attributes frappe.throw(_("Attribute table is mandatory")) File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw msgprint(msg, raise_exception=exc, title=title, indicator=red) File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint _raise_exception() File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception raise raise_exception(encode(msg)) ValidationError: Attribute table is mandatory Failed to send document. Status : Error_sending

**Comment by chdecultot** [comment]
Hi @codrotech,

ERPNext enforces the addition of an attribute table only if you send "1" in the field "has_variant"; else the API requires to send "" (not 0) to create an item without variants.

In general if the error message thrown by Myddleware is originally generated by ERPNext, like the message above, it means it is a problem on ERPNext side (functional or technical).

Hope it helps!

**Comment by codrotech** [comment]
Thanks,

I was able to send products to Erpnext, I created a new rule with just   item_code; item_name, item_group as per minumum requirements for creating new Item and worked.

Now I have to figure out how to sync    Combinations (Presta) and Variants(Erp).

Do you guys have any template on that?

Regards
Maurizio

**Comment by chdecultot** [comment]
Hi @codrotech,

Great that you could make the initial connection.

I haven't been using Myddleware to connect ERPNext with Prestashop yet, so I can only help you with the ERPNext part of it.

To create variants you will need several rules:
1. A rule for the creation of the attributes
2. A rule for the creation of item templates
3. A rule for the creation of variants
4. A child rule for the link with the item attributes

In ERPNext the Template must be present before the creation of the variant. Only then can you run the other rule and create all your variants.

I will try to generate templates as soon as I have some free time. In the meantime I invite you to just try on a test server until you figure out the right combination for your use case.

Best regards,

Charles-Henri

**Comment by codrotech** [comment]
Hi Charles,

Thanks for answer, unfortunately I having trouble at step 2 item template:
" validate_attributes if d.attribute in attributes: AttributeError: unicode object has no attribute attribute Failed to send document. Status : Error_sending"

It seem like a convertion issue since in the field "attributes"  I have my value  "Colour" 

In your steps I think you are missing the creation of Item Variant Attribute.

I'm keep trying thank for help.

**Comment by chdecultot** [comment]
Hi @codrotech,

Yes of course you should link the templates with the attributes in step 2.
For templates you just need to link with the attribute, whereas in step 3 (variants)  you should link with the attribute value. 

It's not an easy task I agree :smiley: 

Good luck!

**Comment by codrotech** [comment]
Ok thanks,

I keep trying, I will keep you updated .
