### ISSUE TITLE
Courses not transferring between Moodle and ERPNext

### ISSUE THREAD

**Issue by himanshunandan** [Myddleware/myddleware#368]
Dear Admin,

My courses are not flowing and I am getting constant error. Screenshot is attached.
Kindly help here.

User data is flowing correctly.

Regards
Himanshu
[course.docx](https://github.com/Myddleware/myddleware/files/5376155/course.docx)

**Comment by Myddleware** [comment]
Hi @himanshunandan ,
The error seems to say that the record you have to send to ERPNext should have a parent record linked. Maybe you have to add a relationship in your rule.
To have more info, you could try to create the record manually in ERPNExt with the data you try to send with Myddleware. Maybe ERPNext UI will give you more detail about the error.
Hope it helps.

**Comment by himanshunandan** [comment]
I tried many times creating a relation.The assessment criteria is not working for me. getting below error:. I have attached screenshot of my rule also. Can you please help here?
[error3.docx](https://github.com/Myddleware/myddleware/files/5377499/error3.docx)

Traceback (most recent call last): File "/home/erpuser/frappe-bench/apps/frappe/frappe/app.py", line 64, in application response = frappe.api.handle() File "/home/erpuser/frappe-bench/apps/frappe/frappe/api.py", line 130, in handle "data": frappe.get_doc(data).insert().as_dict() File "/home/erpuser/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in insert self.run_before_save_methods() File "/home/erpuser/frappe-bench/apps/frappe/frappe/model/document.py", line 896, in run_before_save_methods self.run_method("validate") File "/home/erpuser/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/erpuser/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer return composed(self, method, *args, **kwargs) File "/home/erpuser/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/erpuser/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in &lt;lambda&gt; fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/erpuser/frappe-bench/apps/erpnext/erpnext/education/doctype/course/course.py", line 12, in validate self.validate_assessment_criteria() File "/home/erpuser/frappe-bench/apps/erpnext/erpnext/education/doctype/course/course.py", line 17, in validate_assessment_criteria for criteria in self.assessment_criteria: TypeError: int object is not iterable Failed to send document. Status : Error_sending

**Comment by himanshunandan** [comment]
even if I remove all other fields I see below error. Kindly help here.


Id | Reference | Job | Creation date | Type | Message
-- | -- | -- | -- | -- | --
477 |   | 5f87eb0a33d6b5.48796208 | 15/10/2020 06:24:10 | E | Traceback (most recent call last): File "/home/erpuser/frappe-bench/apps/frappe/frappe/app.py", line 64, in application response = frappe.api.handle() File "/home/erpuser/frappe-bench/apps/frappe/frappe/api.py", line 130, in handle "data": frappe.get_doc(data).insert().as_dict() File "/home/erpuser/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in insert self.run_post_save_methods() File "/home/erpuser/frappe-bench/apps/frappe/frappe/model/document.py", line 941, in run_post_save_methods update_global_search(self) File "/home/erpuser/frappe-bench/apps/frappe/frappe/utils/global_search.py", line 252, in update_global_search if d.parent == doc.name: AttributeError: str object has no attribute parent Failed to send document. Status : Error_sending

**Comment by Myddleware** [comment]
Hi @himanshunandan,
Please try first to create the record manually in ERPNext. Use the same data than in your rule. ERPNext should return an error too. Then try to add other field manually in ERPNExt until the save action works. 
When you successfully create the record manually in ERPNext, do the same in your Myddleware rule, it should work. Myddleware use the same function than ERPNext UI.

**Comment by himanshunandan** [comment]
Thanks for your help. I was able to send the records now.
All set !!

**Comment by Myddleware** [comment]
Thank for your feedback. 
Enjoy Myddleware !
